layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  - tictactoe
  exclude:
    archived: false
    forks: false
    projects:
     - amyhynes.github.io
     - bert
     - COMP550-FinalProject

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: amy-hynes
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://amyhynes.me
  # youtube: your_username

topics:
  - name: Security
    web_url: https://github.com/topics/security
    image_url: https://cdn0.iconfinder.com/data/icons/cybersecurity-linear-outline/300/215948781Untitled-3-512.png

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3xqTfdcuL1QYKCQkFzwX9ZAwHH7KaY0qrplXRwLJtmlqdrvHyUw

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
